version: 1.0.{build}

environment:
  matrix:
    - PIP_INDEX_URL: https://pypi.python.org/simple
    - PIP_EXTRA_INDEX_URL: https://my-extra-pypi
    - PYTHON: "C:\\Python312\\python.exe"

install:
  - python.exe -m pip install --upgrade pip
  - python.exe -m pip install -r requirements.txt

build: false

test: off
