version: 1.0.{build}

environment:
  matrix:
    - PIP_INDEX_URL: https://pypi.python.org/simple
      PIP_EXTRA_INDEX_URL: https://my-extra-pypi
      PYTHON: "C:\\Python39\\python.exe"
    - PIP_INDEX_URL: https://pypi.python.org/simple
      PIP_EXTRA_INDEX_URL: https://my-extra-pypi
      PYTHON: "C:\\Python38\\python.exe"

install:
  - pyhton.exe -m pip install --upgrade pip setuptools wheel
  - pyhton.exe -m pip install -r requirements.txt

build_script:
  - pyhton.exe setup.py sdist bdist_wheel

test_script:
  - pyhton.exe -m pip install -r tests/requirements.txt
  - pytest

after_test:
  - pyhton.exe -m pip install coveralls
  - coveralls

artifacts:
  - path: dist/*
    name: wheels

deploy:
  provider: PyPI
  distribution: sdist
  skip_existing: true
  on:
    branch: main