version: 1.0.{build}

pull_request_matrix:
  - branch: main
    config:
      PULL_REQUEST_NUMBER: $env:APPVEYOR_PULL_REQUEST_NUMBER

init:
  - ps: Install-Product node 16

install:
  - ps: |
      # Установка Python
      If (-Not (Test-Path -Path "$env:USERPROFILE\.virtualenvs")) {
        New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.virtualenvs"
      }
      &{$Branch='dev'; choco install python --version $Branch.}
    Name: Python

  - ps: npm install -g standard
  - ps: npm install
  - ps: python -m pip install --upgrade pip
  - ps: python -m pip install -r requirements.txt

build_script:
  - ps: npm test
  - ps: python setup.py sdist bdist_wheel

test_script:
  - ps: Invoke-WebRequest https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py
  - ps: python get-pip.py
  - ps: python -m pip install virtualenv
  - ps: virtualenv venv
  - ps: .\venv\Scripts\activate.ps1
  - ps: python -m pip install -r requirements.txt
  - ps: pytest

after_build:
  - ps: cp dist/* .

artifacts:
  - path: .\dist\*.whl
    name: wheels
  - path: .\dist\*.tar.gz
    name: source

deploy:
  - provider: TestPywinauto
    artifact: wheels
    script: py -m pip install --upgrade pip
           py -m pip install --force-reinstall --no-index --find-links=. wheels\*
           py -m pytest
  - provider: SimpleHTTP
    artifact: source
    script: echo "No deployment actions required."

branches:
  only:
    - main
    - beta