version: 1.0.{build}

clone_depth: 5

environment:
  matrix:
    - PYTHON: "C:\\Python313\\python.exe"

install:
  - ps: Install-PackageProvider -Name chocolatey -Force
  - ps: choco install python -y
  - ps: refreshenv
  - ps: python -m pip install --upgrade pip setuptools wheel
  - ps: python -m pip install -r requirements.txt

before_build:
  - ps: python -m venv env
  - ps: ./env/Scripts/activate.ps1
  - ps: python setup.py develop

build:
  verbosity: normal

test_script:
  - ps: &run_tests
      pytest --cov=myproject tests
  - ps: coverage xml

after_build:
  - ps: deactivate

artifacts:
  - path: myproject.egg-info\Source\coverage\coverage.xml
    name: Coverage Report

deploy:
  - provider: GitHub
    release: $(APPVEYOR_RELEASENAME)
    description: "Deploying $(APPVEYOR_PROJECT_NAME) version $(APPVEYOR_BUILD_VERSION)"
    auth_token:
      secure: YourSecureToken
    artifact: MyArtifact.zip
    draft: false
    prerelease: false
    on:
      branch: develop

on_success:
  - ps: Write-Host "Successful build!"

on_failure:
  - ps: Write-Host "Failed build!"